BEGIN;


-- =========================================================
-- PEACH SUITE PRO
-- BROWSER SESSION TABS V1
--
-- Server-side presence registry for authenticated PSP
-- browser tabs/windows.
--
-- Raw browser-session markers and tab tokens are never
-- stored. Only SHA-256 hashes are persisted.
--
-- Used to enforce:
--   last PSP tab/window closes -> business login ends
-- =========================================================


CREATE TABLE IF NOT EXISTS browser_session_tabs (

    browser_session_tab_id BIGSERIAL PRIMARY KEY,

    session_marker_hash CHAR(64) NOT NULL,
    tab_token_hash CHAR(64) NOT NULL,

    user_id INTEGER NOT NULL,

    spa_id INTEGER,
    business_unit_id INTEGER,

    opened_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    last_seen_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    closing_at TIMESTAMPTZ,

    updated_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_browser_session_tabs_marker_tab
        UNIQUE (
            session_marker_hash,
            tab_token_hash
        ),

    CONSTRAINT chk_browser_session_tabs_workspace_pair
        CHECK (
            (
                spa_id IS NULL
                AND business_unit_id IS NULL
            )
            OR
            (
                spa_id IS NOT NULL
                AND business_unit_id IS NOT NULL
            )
        ),

    CONSTRAINT fk_browser_session_tabs_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_browser_session_tabs_workspace
        FOREIGN KEY (
            business_unit_id,
            spa_id
        )
        REFERENCES business_units (
            business_unit_id,
            spa_id
        )
        ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS
    idx_browser_session_tabs_marker_seen
ON browser_session_tabs (
    session_marker_hash,
    last_seen_at
);


CREATE INDEX IF NOT EXISTS
    idx_browser_session_tabs_user
ON browser_session_tabs (
    user_id
);


CREATE INDEX IF NOT EXISTS
    idx_browser_session_tabs_closing_at
ON browser_session_tabs (
    closing_at
)
WHERE closing_at IS NOT NULL;


CREATE INDEX IF NOT EXISTS
    idx_browser_session_tabs_open_last_seen
ON browser_session_tabs (
    last_seen_at
)
WHERE closing_at IS NULL;


COMMENT ON TABLE browser_session_tabs
IS
    'Short-lived server-side presence registry used to '
    'determine whether an authenticated Peach Suite Pro '
    'browser session still has an open PSP tab or window.';


COMMENT ON COLUMN
    browser_session_tabs.session_marker_hash
IS
    'SHA-256 hash of the authenticated browser-session marker.';


COMMENT ON COLUMN
    browser_session_tabs.tab_token_hash
IS
    'SHA-256 hash of a random token generated by one PSP '
    'browser page/tab instance. Raw tokens are never stored.';


COMMENT ON COLUMN
    browser_session_tabs.closing_at
IS
    'Timestamp when the browser page reported pagehide/close. '
    'A short grace period permits ordinary PSP navigation or '
    'refresh to register the replacement page before the '
    'business session is considered closed.';


COMMIT;
